symbol: "588000"
etf_pool:
  "510300": "沪深300ETF"      # 大盘基准
  "510500": "中证500ETF"      # 中小盘
  "159915": "创业板ETF"       # 成长风格
  "512880": "证券ETF"         # 强周期
  "510880": "红利ETF"         # 防御价值
  "513100": "纳指ETF"         # 海外资产
  "512660": "军工ETF"         # 独立行情
  "511260": "国债ETF"         # 避险资产
  "159949": "黄金ETF"         # 大宗商品
# etf_pool:
  # "510300": "沪深300ETF"      # 大盘基准
  # # "518880": "黄金ETF"         # 大宗商品
  # "513100": "纳指100ETF"      # 海外资产
  # "513030": "德国ETF"         # 德国
  # "513090": "港股ETF"         # 港股
  # "159915": "创业板100ETF"    # 成长股，科技股，中小盘
  # "510180": "上证180ETF"      # 价值股，蓝筹股，中大盘
  # "511010": "国债ETF"         # 防守型

# start_date: "20210101"
# end_date: "20251231"

# start_date: "20200101"
# end_date: "20201231"

start_date: "20250101"
end_date: "20251231"

initial_cash: 100000.0
asset_type: "stock"
lot_size: 100
commission_rate: 0.0003
strategy: "RotationStrategy" # "DoubleMAStrategy" "AgentStrategy" "BenchmarkStrategy" "RotationStrategy"